/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ConexionMySQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arkanakin
 */
public class Main extends javax.swing.JFrame {
    DefaultTableModel modelo; //Modelo de la tabla
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    public void consulta(){
        String encabezados[] = {"Nombre", "Dirección", "Telefono", "Correo", "País", "Edad", "Sexo"};
        String fila[] = new String[7];
        
        modelo = new DefaultTableModel(null, encabezados);
        
        ConexionMySQL mysql = new ConexionMySQL();
        Connection conexion = mysql.conectar();
        
        String query = "SELECT * FROM maestros";
        
        Statement st;
        try {
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            //Valida un unico registro del query
            //rs.first(); //jalar el valor del query
            
            while(rs.next()){
            
                fila[0] = rs.getString("nombre");
                fila[1] = rs.getString("direccion");
                fila[2] = rs.getString("telefono");
                fila[3] = rs.getString("correo");
                fila[4] = rs.getString("pais");
                fila[5] = rs.getString("edad");
                fila[6] = rs.getString("sexo");

                modelo.addRow(fila); //asignamos el arreglo al modelo
            } //while
            tblGrupos.setModel(modelo); //asignamos el arreglo a la tabla
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnInicio = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrupos = new javax.swing.JTable();
        mnbPrincipal = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuProfesores = new javax.swing.JMenu();
        mitAgregarProfesor = new javax.swing.JMenuItem();
        mitConsultarProfesor = new javax.swing.JMenuItem();
        mitEditarProfesor = new javax.swing.JMenuItem();
        mitEliminarProfesor = new javax.swing.JMenuItem();
        mnuGrupos = new javax.swing.JMenu();
        mnuAlumnos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA ESCOLAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(438, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setRollover(true);

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_School_48px.png"))); // NOI18N
        btnInicio.setText("Inicio ");
        jToolBar1.add(btnInicio);

        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Training_48px.png"))); // NOI18N
        btnProfesores.setText("Profesores ");
        btnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProfesores);

        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Graduation_Cap_48px.png"))); // NOI18N
        btnAlumnos.setText("Alumnos ");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlumnos);

        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Course_40px.png"))); // NOI18N
        btnMaterias.setText("Materias ");
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMaterias);

        tblGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblGrupos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
        );

        mnuArchivo.setText("File");
        mnbPrincipal.add(mnuArchivo);

        mnuProfesores.setText("Profesores");

        mitAgregarProfesor.setText("Agregar");
        mitAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAgregarProfesorActionPerformed(evt);
            }
        });
        mnuProfesores.add(mitAgregarProfesor);

        mitConsultarProfesor.setText("Consutar");
        mnuProfesores.add(mitConsultarProfesor);

        mitEditarProfesor.setText("Editar");
        mnuProfesores.add(mitEditarProfesor);

        mitEliminarProfesor.setText("Eliminar");
        mnuProfesores.add(mitEliminarProfesor);

        mnbPrincipal.add(mnuProfesores);

        mnuGrupos.setText("Grupos");
        mnbPrincipal.add(mnuGrupos);

        mnuAlumnos.setText("Alumnos");
        mnbPrincipal.add(mnuAlumnos);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        new AltaMaestros().setVisible(true); //Abrir ventana Maestros
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        new AltaAlumnos().setVisible(true); //Abrir ventana Alumnos
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        new AltaGrupos().setVisible(true); //Abrir ventana Grupos
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void mitAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAgregarProfesorActionPerformed
        new AltaGrupos().setVisible(true);
    }//GEN-LAST:event_mitAgregarProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mitAgregarProfesor;
    private javax.swing.JMenuItem mitConsultarProfesor;
    private javax.swing.JMenuItem mitEditarProfesor;
    private javax.swing.JMenuItem mitEliminarProfesor;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenu mnuAlumnos;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuGrupos;
    private javax.swing.JMenu mnuProfesores;
    private javax.swing.JTable tblGrupos;
    // End of variables declaration//GEN-END:variables
}
